// Generated by https://quicktype.io

export interface Contract {
  id:        number;
  startDate: number[]; // [YYYY, MM, DD]
  endDate:   number[]; // [YYYY, MM, DD]
  rent:      string;
  deposit:   string;
  status:    string;
  userId:    number;
  propertyId:  number;
}
