// Generated by https://quicktype.io

export interface Property {
  id:                 number;
  name:               string;
  address:            string;
  price:              string;
  squareFeet:         string;
  bedrooms:           number;
  bathrooms:          number;
  garage:             boolean;
  patio:              boolean;
  elevator:           boolean;
  typeOfProperty:     number;
  furnitureInventory: null | number;
}
